name: Bug Fix
description: Track a bug that needs to be fixed
title: "[Bug]: "
labels: ["bug", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Developer workflow for tracking and fixing bugs

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What's the bug?
      value: |

    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      value: |

    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: File/Component Location
      description: Where is the bug located?
      placeholder: e.g., src/components/Header.tsx:42

  - type: textarea
    id: root-cause
    attributes:
      label: Root Cause Analysis
      description: What's causing this bug?
      value: |

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How will you fix it?
      value: |

  - type: textarea
    id: testing
    attributes:
      label: Testing Plan
      description: How will you verify the fix?
      value: |
        - [ ] Manual testing steps
        - [ ] Unit tests added
        - [ ] Edge cases covered

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical/Blocking
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true

  - type: input
    id: assignee
    attributes:
      label: Assignee
      description: Who's working on this?
      placeholder: "@username"
