name: Feature Development
description: Track development of a new feature
title: "[Feature]: "
labels: ["feature", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Developer workflow for building new features

  - type: textarea
    id: overview
    attributes:
      label: Feature Overview
      description: What are we building?
      placeholder: Brief description of the feature
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: What does this feature need to do?
      placeholder: |
        - Requirement 1
        - Requirement 2
        - Requirement 3
    validations:
      required: true

  - type: textarea
    id: technical-design
    attributes:
      label: Technical Design
      description: How will this be implemented?
      placeholder: |
        **Components:**
        - Component 1
        - Component 2

        **State Management:**
        - What state is needed

        **API/Backend:**
        - Endpoints needed

        **Database:**
        - Schema changes

  - type: textarea
    id: tasks
    attributes:
      label: Implementation Tasks
      description: Break down the work
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
        - [ ] Write tests
        - [ ] Update documentation
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What needs to happen first?
      placeholder: |
        - Blocked by #123
        - Needs design approval
        - Requires API endpoint from backend

  - type: textarea
    id: testing-plan
    attributes:
      label: Testing & QA Plan
      description: How will this be tested?
      placeholder: |
        **Unit Tests:**
        - [ ] Test case 1

        **Integration Tests:**
        - [ ] Test case 2

        **Manual Testing:**
        - [ ] Test scenario 1

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical/Blocking
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      options:
        - XS - Few hours
        - S - 1-2 days
        - M - 3-5 days
        - L - 1-2 weeks
        - XL - 2+ weeks
    validations:
      required: true

  - type: input
    id: assignee
    attributes:
      label: Assignee
      description: Who's building this?
      placeholder: "@username"
